custom:
  baseName: ${opt:stage}-${self:service}
frameworkVersion: '3'
functions:
  servicea:
    handler: lambda_2.handler
    name: ${self:custom.baseName}
provider:
  name: aws
  runtime: python3.9
  environment:
    test1: hola_lambda
service: lambda2
