custom:
  projectName: stack-2-project-1
  baseName: ${self:custom.projectName}-${opt:stage}-${self:service}
frameworkVersion: '3'
functions:
  servicea-stack2:
    handler: lambda_1.hello
    name: ${self:custom.baseName}
provider:
  name: aws
  runtime: python3.9
  environment:
    test1: hola
service: lambda1-stack2
